### ISSUE TITLE
Kentucky is out of date

### ISSUE THREAD

**Issue by rkahne** [nvkelso/election-geodata#103]
Hello friend,

I am a co-captain with the Civic Data Alliance, the group which you pulled the KY data from.  Our map is out of date as of 2015.  We have been working to get a new shapefile with the most recent election, but progress has been slow.

**Comment by migurski** [comment]
Thanks for the information, Robert! Do you recommend that we change anything here?

**Comment by rkahne** [comment]
Depends on what you want to do.  These precincts will not work with the 2015 nor 2016 elections.

**Comment by nvkelso** [comment]
@rkahne Thanks for the clarification! I'll update the year on this line to be `2014` instead of `2016`:

- https://github.com/nvkelso/election-geodata/blob/master/Makefile#L484

Do you know if these 2014 shapes were also good for prior elections like 2012?

(I've also re-opened https://github.com/nvkelso/election-geodata/issues/29 to track adding the newer 2016 data.)

**Comment by rkahne** [comment]
Unfortunately, I can't speak to the whole state, just Jefferson County, which I know was the same dating back to 2012.
